version: '3'
services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file: './env.sh'
  nginx:
    container_name: nginx
    depends_on:
      - api
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '3050:80'
  api:
    container_name: api
    build:
      context: './server'
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
      - PGHOST=postgres
      - PGPORT=${POSTGRES_PORT}
    env_file: './env.sh'
